server:
  port: 8097

spring:
  application:
    name: subscription-service
  datasource:
    url: jdbc:mysql://100.122.144.43:3306/food_app
    username: teamuser
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  activemq:
    broker-url: tcp://localhost:61616
    user: Deepak
    password: Deepak123
    pool:
      enabled: true
      max-connections: 50

subscription:
  plans:
    cache-ttl: 3600 # 1 hour
  payment:
    retry:
      max-attempts: 3
      interval: 86400 # 24 hours
  notification:
    reminder-days: 3
  benefits:
    free-delivery:
      min-order: 15.00
    cashback:
      percentage: 5
    priority-support: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  retry:
    instances:
      subscriptionRenewal:
        maxRetryAttempts: 3
        waitDuration: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodapp.subscription: DEBUG