server:
  port: 8096

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/foodapp_analytics
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/foodapp_analytics
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-service-group
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: ${ELASTIC_USERNAME}
      password: ${ELASTIC_PASSWORD}

analytics:
  batch:
    enabled: true
    schedule: "0 0 * * * *" # Every hour
  retention:
    raw-data: 90 # days
    aggregated-data: 365 # days
  reporting:
    enabled: true
    export-formats: pdf,csv,excel
  real-time:
    enabled: true
    update-interval: 60 # seconds

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      dataCollection:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
  bulkhead:
    instances:
      reporting:
        maxConcurrentCalls: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodapp.analytics: DEBUG