server:
  port: 8091
  
spring:
  application:
    name: ai-service
  
  data:
    mongodb:
      database: aiservice_db
      uri: mongodb://localhost:27017/aiservice_db
      
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: hungrycheetah62@gmail.com
    password: feat seix sqbb lvhz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

gemini:
  api:
    key: AIzaSyAb8RN6JeM3nTi5ipNIjZhzuVExA-bYRshFGCdCN86mS5gfdi2g
    base-url: https://generativelanguage.googleapis.com/v1beta
    model: gemini-1.5-flash
    timeout: 30000
    max-tokens: 1000
    temperature: 0.7

logging:
  level:
    com.foodapp.aiservice: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always