server:
  port: 8103

spring:
  application:
    name: promotion-service
  datasource:
    url: jdbc:mysql://100.122.144.43:3306/food_app
    username: teamuser
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  activemq:
    broker-url: tcp://100.122.144.43:61616
    user: Deepak
    password: Deepak123
    pool:
      enabled: true
      max-connections: 50


promotion:
  validation:
    enabled: true
    cache-ttl: 300 # 5 minutes
  limits:
    max-discount-percentage: 70
    min-order-amount: 15.00
    max-uses-per-user: 5
  types:
    - PERCENTAGE_DISCOUNT
    - FLAT_DISCOUNT
    - BUY_ONE_GET_ONE
    - FREE_DELIVERY
  targeting:
    enabled: true
    rules:
      - new-users
      - inactive-users
      - high-value-users

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodapp.promotion: DEBUG