server:
  port: 8103

spring:
  application:
    name: promotion-service
  datasource:
    url: jdbc:postgresql://localhost:5432/foodapp_promotions
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: promotion-service-group


promotion:
  validation:
    enabled: true
    cache-ttl: 300 # 5 minutes
  limits:
    max-discount-percentage: 70
    min-order-amount: 15.00
    max-uses-per-user: 5
  types:
    - PERCENTAGE_DISCOUNT
    - FLAT_DISCOUNT
    - BUY_ONE_GET_ONE
    - FREE_DELIVERY
  targeting:
    enabled: true
    rules:
      - new-users
      - inactive-users
      - high-value-users

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      promotionValidation:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
  ratelimiter:
    instances:
      codeGeneration:
        limitForPeriod: 100
        limitRefreshPeriod: 1m

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodapp.promotion: DEBUG