server:
  port: 8101

spring:
  application:
    name: loyalty-service
  datasource:
    url: jdbc:mysql://100.122.144.43:3306/food_app
    username: teamuser
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  activemq:
    broker-url: tcp:// 100.122.144.43:61616
    user: Deepak
    password: Deepak123
    pool:
      enabled: true
      max-connections: 50


loyalty:
  points:
    expiry-months: 12
    minimum-redemption: 100
    earn-rate: 1 # points per dollar
  tiers:
    - name: BRONZE
      minimum-points: 0
      benefits:
        - type: CASHBACK
          value: 1
    - name: SILVER
      minimum-points: 1000
      benefits:
        - type: CASHBACK
          value: 2
    - name: GOLD
      minimum-points: 5000
      benefits:
        - type: CASHBACK
          value: 5
  special-events:
    birthday-multiplier: 2
    holiday-multiplier: 1.5

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      pointsCalculation:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
  retry:
    instances:
      pointsUpdate:
        maxRetryAttempts: 3
        waitDuration: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodapp.loyalty: DEBUG