server:
  port: 8093

spring:
  application:
    name: recommendation-service
  datasource:
    url: jdbc:postgresql://localhost:5432/foodapp_recommendations
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/foodapp_recommendations
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD}

recommendation:
  cache:
    ttl: 3600 # 1 hour in seconds
  algorithm:
    weight:
      user-preference: 0.4
      order-history: 0.3
      popularity: 0.2
      seasonal: 0.1
  batch:
    update-interval: 86400 # 24 hours in seconds

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userService:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
      orderService:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
  bulkhead:
    instances:
      recommendationGeneration:
        maxConcurrentCalls: 20

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodapp.recommendation: DEBUG