server:
  port: 8099

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:postgresql://localhost:5432/foodapp_admin
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: admin-service-group
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD}

admin:
  security:
    jwt:
      secret: ${ADMIN_JWT_SECRET}
      expiration: 28800 # 8 hours
  audit:
    enabled: true
    retention: 90 # days
  dashboard:
    refresh-interval: 30 # seconds

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userManagement:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
  ratelimiter:
    instances:
      adminOperations:
        limitForPeriod: 100
        limitRefreshPeriod: 1m

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodapp.admin: DEBUG