server:
  port: 8098

spring:
  application:
    name: social-service
  datasource:
    url: jdbc:postgresql://localhost:5432/foodapp_social
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/foodapp_social
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: social-service-group
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD}

social:
  feed:
    cache-ttl: 300 # 5 minutes
    page-size: 20
  media:
    storage:
      path: ${MEDIA_STORAGE_PATH}
      max-size: 10MB
  moderation:
    enabled: true
    ai-assisted: true
  interaction:
    rate-limit: 100 # per minute

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userService:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
  ratelimiter:
    instances:
      postCreation:
        limitForPeriod: 10
        limitRefreshPeriod: 1m
        timeoutDuration: 5s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodapp.social: DEBUG