server:
  port: 8094

spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5432/foodapp_drivers
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: driver-service-group


driver:
  location:
    update-interval: 15 # seconds
  assignment:
    radius: 5 # kilometers
    max-concurrent-orders: 2
  verification:
    document-path: ${DOCUMENT_STORAGE_PATH}
  rating:
    minimum-threshold: 4.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      locationService:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
  bulkhead:
    instances:
      driverAssignment:
        maxConcurrentCalls: 20

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodapp.driver: DEBUG