package com.foodapp.ai.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Service
public class AIEmailService {
    private static final Logger logger = LoggerFactory.getLogger(AIEmailService.class);
    
    private final JavaMailSender mailSender;
    
    @Value("${spring.mail.username}")
    private String fromEmail;

    @Autowired
    public AIEmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    public void sendRecommendationEmail(String toEmail, String userName, String recommendations) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true);

            helper.setFrom(fromEmail);
            helper.setTo(toEmail);
            helper.setSubject("🍽️ Your Personalized Food Recommendations - HungryCheetah");

            String htmlContent = String.format("""
                <html>
                <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                    <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
                        <h2 style="color: #ff6b35; text-align: center;">🍽️ Your AI-Powered Food Recommendations</h2>
                        
                        <p>Dear %s,</p>
                        
                        <p>Our AI chef has prepared some delicious recommendations just for you! 🤖👨‍🍳</p>
                        
                        <div style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid #ff6b35; margin: 20px 0;">
                            <h3 style="color: #ff6b35; margin-top: 0;">Today's Recommendations:</h3>
                            <div style="white-space: pre-line;">%s</div>
                        </div>
                        
                        <p><strong>Why these recommendations?</strong></p>
                        <ul>
                            <li>✨ Personalized based on your taste preferences</li>
                            <li>🥗 Considers your dietary requirements</li>
                            <li>📍 Available at nearby restaurants</li>
                            <li>⭐ Highly rated by other users</li>
                        </ul>
                        
                        <div style="text-align: center; margin: 30px 0;">
                            <p style="color: #666;">Ready to order? Open the HungryCheetah app and explore these delicious options!</p>
                        </div>
                        
                        <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
                        <p style="font-size: 12px; color: #666; text-align: center;">
                            Generated by HungryCheetah AI • %s<br>
                            Don't like these recommendations? Update your preferences in the app for better suggestions!
                        </p>
                    </div>
                </body>
                </html>
                """, 
                userName, 
                recommendations,
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMM dd, yyyy 'at' HH:mm"))
            );

            helper.setText(htmlContent, true);
            mailSender.send(message);
            logger.info("Recommendation email sent successfully to: {}", toEmail);
            
        } catch (MessagingException e) {
            logger.error("Failed to send recommendation email to: " + toEmail, e);
        }
    }

    public void sendNutritionAnalysisEmail(String toEmail, String userName, String foodItem, String analysis) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true);

            helper.setFrom(fromEmail);
            helper.setTo(toEmail);
            helper.setSubject("🥗 Nutrition Analysis: " + foodItem + " - HungryCheetah");

            String htmlContent = String.format("""
                <html>
                <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                    <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
                        <h2 style="color: #28a745; text-align: center;">🥗 Nutrition Analysis Report</h2>
                        
                        <p>Dear %s,</p>
                        
                        <p>Here's the detailed nutrition analysis for <strong>%s</strong> that you requested:</p>
                        
                        <div style="background-color: #f8f9fa; padding: 15px; border-left: 4px solid #28a745; margin: 20px 0;">
                            <h3 style="color: #28a745; margin-top: 0;">Nutrition Information:</h3>
                            <div style="white-space: pre-line;">%s</div>
                        </div>
                        
                        <div style="background-color: #e7f3ff; padding: 15px; border-radius: 5px; margin: 20px 0;">
                            <h4 style="color: #0056b3; margin-top: 0;">💡 Health Tips:</h4>
                            <ul style="margin: 10px 0;">
                                <li>Consider portion sizes for optimal nutrition</li>
                                <li>Balance with other food groups throughout the day</li>
                                <li>Stay hydrated and maintain regular meal times</li>
                            </ul>
                        </div>
                        
                        <div style="text-align: center; margin: 30px 0;">
                            <p style="color: #666;">Track your nutrition goals in the HungryCheetah app!</p>
                        </div>
                        
                        <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
                        <p style="font-size: 12px; color: #666; text-align: center;">
                            Generated by HungryCheetah AI Nutritionist • %s<br>
                            Consult with a healthcare professional for personalized nutrition advice.
                        </p>
                    </div>
                </body>
                </html>
                """, 
                userName, 
                foodItem,
                analysis,
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMM dd, yyyy 'at' HH:mm"))
            );

            helper.setText(htmlContent, true);
            mailSender.send(message);
            logger.info("Nutrition analysis email sent successfully to: {}", toEmail);
            
        } catch (MessagingException e) {
            logger.error("Failed to send nutrition analysis email to: " + toEmail, e);
        }
    }

    public void sendRecipeEmail(String toEmail, String userName, String dishName, String recipe) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true);

            helper.setFrom(fromEmail);
            helper.setTo(toEmail);
            helper.setSubject("👨‍🍳 Recipe: " + dishName + " - HungryCheetah AI Chef");

            String htmlContent = String.format("""
                <html>
                <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                    <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
                        <h2 style="color: #dc3545; text-align: center;">👨‍🍳 Your AI-Generated Recipe</h2>
                        
                        <p>Dear %s,</p>
                        
                        <p>Here's your custom recipe for <strong>%s</strong>, created by our AI chef! 🤖👨‍🍳</p>
                        
                        <div style="background-color: #fff8dc; padding: 15px; border-left: 4px solid #dc3545; margin: 20px 0;">
                            <h3 style="color: #dc3545; margin-top: 0;">Recipe Details:</h3>
                            <div style="white-space: pre-line;">%s</div>
                        </div>
                        
                        <div style="background-color: #f0f8ff; padding: 15px; border-radius: 5px; margin: 20px 0;">
                            <h4 style="color: #0066cc; margin-top: 0;">🍳 Cooking Tips:</h4>
                            <ul style="margin: 10px 0;">
                                <li>Read through the entire recipe before starting</li>
                                <li>Prep all ingredients beforehand (mise en place)</li>
                                <li>Taste and adjust seasonings as needed</li>
                                <li>Don't be afraid to make it your own!</li>
                            </ul>
                        </div>
                        
                        <div style="text-align: center; margin: 30px 0;">
                            <p style="color: #666;">Share your cooking results on social media and tag us! #HungryCheetahRecipe</p>
                        </div>
                        
                        <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
                        <p style="font-size: 12px; color: #666; text-align: center;">
                            Generated by HungryCheetah AI Chef • %s<br>
                            Save this recipe in the app for easy access while cooking!
                        </p>
                    </div>
                </body>
                </html>
                """, 
                userName, 
                dishName,
                recipe,
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMM dd, yyyy 'at' HH:mm"))
            );

            helper.setText(htmlContent, true);
            mailSender.send(message);
            logger.info("Recipe email sent successfully to: {}", toEmail);
            
        } catch (MessagingException e) {
            logger.error("Failed to send recipe email to: " + toEmail, e);
        }
    }

    public void sendFeedbackThankYouEmail(String toEmail, String userName) {
        try {
            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom(fromEmail);
            message.setTo(toEmail);
            message.setSubject("🙏 Thank You for Your Feedback - HungryCheetah AI");
            
            String content = String.format("""
                Dear %s,
                
                Thank you for providing feedback on our AI recommendations! 🙏
                
                Your input helps our AI learn and improve to provide you with even better food suggestions in the future.
                
                We're constantly working to enhance your HungryCheetah experience with:
                • More accurate personalized recommendations
                • Better understanding of your taste preferences
                • Improved meal suggestions based on your feedback
                
                Keep exploring delicious food with HungryCheetah AI! 🍽️✨
                
                Best regards,
                The HungryCheetah AI Team
                
                ---
                Generated on %s
                """, 
                userName,
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMM dd, yyyy 'at' HH:mm"))
            );

            message.setText(content);
            mailSender.send(message);
            logger.info("Feedback thank you email sent successfully to: {}", toEmail);
            
        } catch (Exception e) {
            logger.error("Failed to send feedback thank you email to: " + toEmail, e);
        }
    }
}