server:
  port: 8105

spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: foodapp-search
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: search-service-group
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD}

search:
  indexing:
    batch-size: 1000
    schedule: "0 0 * * * *" # Every hour
  cache:
    ttl: 300 # 5 minutes
  features:
    autocomplete: true
    fuzzy-search: true
    geo-search: true
  ranking:
    factors:
      relevance: 0.4
      rating: 0.3
      distance: 0.2
      popularity: 0.1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      searchOperation:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
  bulkhead:
    instances:
      searchRequests:
        maxConcurrentCalls: 50

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodapp.search: DEBUG
    org.elasticsearch: INFO