server:
  port: 8106

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://100.122.144.43:3306/food_app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: teamuser
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
  
  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: hungrycheetah62@gmail.com
    password: feat seix sqbb lvhz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com


notification:
  providers:
    email:
      enabled: true
      smtp:
        host: smtp.gmail.com
        port: 587
        username: hungrycheetah62@gmail.com
        password: feat seix sqbb lvhz
    sms:
      enabled: true
      twilio:
        account-sid: ${TWILIO_ACCOUNT_SID:}
        auth-token: ${TWILIO_AUTH_TOKEN:}
        phone-number: ${TWILIO_PHONE_NUMBER:}
    push:
      enabled: true
      firebase:
        config-path: ${FIREBASE_CONFIG_PATH:}
  templates:
    cache-ttl: 3600 # 1 hour
  retry:
    max-attempts: 3
    initial-interval: 1000 # milliseconds
    multiplier: 2.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
      smsProvider:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        limitRefreshPeriod: 1m

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.foodapp.notification: DEBUG